name: lcm_dart
description: Dart bindings and code generator for LCM (Lightweight Communications and Marshalling)
version: 1.5.1
repository: https://github.com/lcm-proj/lcm

environment:
  sdk: ^3.0.0

dependencies:
  build: ^2.4.0
  build_config: ^1.1.0
  glob: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.2.0
  test: ^1.24.0
